# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.name: 'Location des salles du CD08'
    app.mailer_from: '%env(MAILER_FROM)%'
    github.repo: 'frdemoulin08/reservation-salle'
    ban_api_base: 'https://api-adresse.data.gouv.fr'
    company_api_base: 'https://recherche-entreprises.api.gouv.fr'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Service\GitHubVersionService:
        arguments:
            $githubRepo: '%github.repo%'

    App\Menu\BackofficeMenuBuilder:
        arguments:
            $configProvider: '@App\Service\BackofficeMenuConfigProvider'

    App\Service\BackofficeMenuConfigProvider:
        arguments:
            $defaultConfig: '%backoffice_menu%'

    App\Service\BanAddressClient:
        arguments:
            $baseUrl: '%ban_api_base%'

    App\Service\CompanyLookupService:
        arguments:
            $baseUrl: '%company_api_base%'

    App\Service\SiteDocumentStorage:
        arguments:
            $publicFilesystem: '@site_public_filesystem'
            $privateFilesystem: '@site_private_filesystem'

    App\Service\RoomDocumentStorage:
        arguments:
            $publicFilesystem: '@site_public_filesystem'
            $privateFilesystem: '@site_private_filesystem'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
